### ISSUE TITLE
Favor de depositar sus archivos de demos, calculadora, MVC en su directorio

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/iOS#2]
## Favor de depositar sus archivos de demos, calculadora, MVC en su directorio, el pantallazo no tiene el valor que es la distribución de su software por Git Pull.

![](http://www.angusyoung.org/wp-content/uploads/2013/05/KeepCalmStudio.com-Crown-Keep-Calm-And-Git-Push.png)

@tectijuana/patrones

**Comment by Alan8a** [comment]
Si profesor, en eso estoy
